apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  name: geonode
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: http-alt
    - name: "https"
      port: 443
      targetPort: https-alt
  selector:
    {{- include "nginx.selectorLabels" . | nindent 6 }}
status:
  loadBalancer: {}
