apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "geonode.statics-pvc" . }}
  labels:
    {{- include "geonode.labels" . | nindent 4 }}
{{- with .Values.volumes.statics }}
  {{- if .keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  volumeMode: Filesystem
  {{- if .volumeName }}
  volumeName: {{ .volumeName | quote }}
  {{- end }}
  accessModes:
    {{- range .storage.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .volumeName }}
  storageClassName: "" 
  {{- else if .storage.className }} 
  storageClassName: {{ .storage.className | quote }} 
  {{- end }}
  resources:
    requests:
      storage: {{ .storage.size }}
{{- end }}
